### ISSUE TITLE
validate-token-header - does it really validate?

### ISSUE THREAD

**Issue by ghoshsanjoy78** [playerony/validate-azure-ad-token#8]
Hi,

I was just looking at the code for validate-token-header.ts and I am confused by what it does. It seems all validate-token-header is doing is getting a public key corresponding to the tokenHeader.kid property. After that it does not really validate the token using the public key. Is that correct?

`  const isValidPublicKey = data.keys.some((_key) => _key.kid === tokenHeader.kid);
  if (!isValidPublicKey) {
    throw new Error('The public key retrieved from the token header is invalid');
  }
`

Thanks,
Sanjoy

**Comment by stijnbuurman** [comment]
I started looking into this package and this is a valid concern. This package does not seem to validate the signature of the token. Look at https://github.com/justinlettau/azure-ad-verify-token to see how to properly validate

**Comment by coreprocess** [comment]
https://github.com/playerony/validate-azure-ad-token/issues/28
